class Config(object):
    DATABASE_FILE   = "app/database/appdata.db"
    USER_NAME       = "ALX.ZYUZIN@GMAIL.COM"
    USER_PASSWORD   = "PASSWORD"
    SECRET_KEY      = "IkqQWV907tMmatKFsPccU6kk5L_mDfWzPUaji_3vWRk"
    SQLALCHEMY_DATABASE_URI = "sqlite:///appdata.db"
    SQLALCHEMY_TRACK_MODIFICATIONS = False


class InitialIndicatorsParams(object):
    USERID = ""
    SIMBOL = "-----"

    WIDTH = 800
    HEIGH = 600

    HISTORY_LENGTH = 250
    DAILY_PRICES_COLOR = "AAAAAA"

    MA_FIRST_PERIOD = 4
    MA_FIRST_TYPE = "sma"
    MA_FIRST_COLOR = 'FFFF00'
    SHOW_MA_FIRST = True

    MA_SECOND_PERIOD = 9
    MA_SECOND_TYPE = "ema"
    MA_SECOND_COLOR = '00FF00'
    SHOW_MA_SECOND = True

    MA_THIRD_PERIOD = 18
    MA_THIRD_TYPE = "ema"
    MA_THIRD_COLOR = '0000FF'
    SHOW_MA_THIRD = True

    VOLUME_COLOR = "0000FF"
    SHOW_VOLUME = True

    RSI_PERIOD = 20
    RSI_COLOR = "00FF00"    
    SHOW_RSI = True    
    
    MACD_SHORT_PERIOD = 12
    MACD_LONG_PERIOD = 26
    MACD_SIGNAL_PERIOD = 9 
    MACD_MAIN_COLOR = "0000FF"
    MACD_SIGNAL_COLOR = "FF0000"    
    SHOW_MACD = True
    
    BOLLINGERBAND_PERIOD = 20
    BOLLINGERBAND_PROBABILITY = 90
    BOLLINGERBAND_COLOR = "00FF00"
    BOLLINGERBAND_OPACITY = 0.2
    SHOW_BOLINGERBAND = True
    